=== BillTheBest/wavemaker/dev/core/tools/src/main/resources/com/wavemaker/tools/deployment/xmlhandlers/deploymentTargets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Targets" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Targets" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Target">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" minOccurs="0" />
              <xs:element name="description" type="xs:string" minOccurs="0" />
              <xs:element name="destType" minOccurs="0">
		<xs:simpleType>
		  <xs:restriction base="xs:string">
		    <xs:enumeration value="server"/>
		    <xs:enumeration value="storage"/>
		  </xs:restriction>
	        </xs:simpleType>
	      </xs:element>
              <xs:element name="serviceProvider" minOccurs="0">
	        <xs:simpleType>
		  <xs:restriction base="xs:string">
		    <xs:enumeration value="local"/>
		    <xs:enumeration value="amazon"/>
		    <xs:enumeration value="opsource"/>
		    <xs:enumeration value="rackspace"/>
		  </xs:restriction>
	        </xs:simpleType>
	      </xs:element>
              <xs:element name="server" minOccurs="0">
	        <xs:simpleType>
		  <xs:restriction base="xs:string">
		    <xs:enumeration value="tomcat"/>
		    <xs:enumeration value="websphere"/>
		  </xs:restriction>
		</xs:simpleType>
	      </xs:element>
              <xs:element name="container" type="xs:string" minOccurs="0" />
              <xs:element name="dnsHost" type="xs:string" minOccurs="0" />
              <xs:element name="publicIp" type="xs:string" minOccurs="0" />
              <xs:element name="privateIp" type="xs:string" minOccurs="0" />
              <xs:element name="port" type="xs:string" minOccurs="0" />
              <xs:element name="user" type="xs:string" minOccurs="0" />
              <xs:element name="password" type="xs:string" minOccurs="0" />
              <xs:element name="OS" minOccurs="0">
	        <xs:simpleType>
		  <xs:restriction base="xs:string">
		    <xs:enumeration value="windows"/>
		    <xs:enumeration value="linux"/>
		    <xs:enumeration value="unix"/>
		  </xs:restriction>
	        </xs:simpleType>
	      </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BillTheBest/wavemaker/dev/core/tools/src/com/wavemaker/tools/deployment/xmlhandlers/deploymentTargets.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Targets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///./deploymentTargets.xsd">
    <Target>
        <name>target1</name>
        <description>local tomcat</description>
		<destType>server</destType>
		<serviceProvider>local</serviceProvider>
        <server>tomcat</server>
		<container></container>
		<dnsHost>localhost</dnsHost>
		<publicIp></publicIp>
		<privateIp></privateIp>
        <port>8080</port>
		<user>manager</user>
		<password>manager</password>
        <OS>windows</OS>
    </Target>
    <Target>
        <name>target2</name>
        <description>CloudFoundry</description>
        <destType>server</destType>
        <serviceProvider>CloudFoundry</serviceProvider>
        <server>cloudfoundry</server>
        <container></container>
        <dnsHost>api.cloudfoundry.com</dnsHost>
        <publicIp></publicIp>
        <privateIp></privateIp>
        <port></port>
        <user></user>
        <password></password>
        <OS>linux</OS>
    </Target>
	<Target>
        <name>target3</name>
        <description>local websphere</description>
		<destType>server</destType>
		<serviceProvider>local</serviceProvider>
        <server>websphere</server>
		<container></container>
		<dnsHost>localhost</dnsHost>
		<publicIp></publicIp>
		<privateIp></privateIp>
        <port>8880</port>
		<user></user>
		<password></password>
        <OS>windows</OS>
    </Target>
</Targets>
